# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bj.form_authenticator:
        class: BJ\UserBundle\Security\FormAuthenticator
        arguments: ["@security.password_encoder", "@router"]
        autowire: true

    bj.form.form_tags:
        class: BJ\LinksBundle\Form\Type\TagType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }